# Generated by Django 5.2.4 on 2025-11-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blog', '0005_post_doodle'), ('blog', '0006_remove_post_doodle_doodle'), ('blog', '0007_post_doodle_delete_doodle'), ('blog', '0008_rename_doodle_post_canva')]

    dependencies = [
        ('blog', '0004_post_is_active_articlereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canva',
            field=models.JSONField(null=True),
        ),
    ]
